services:
  db:
    image: postgres:15
    container_name: mirahub_db
    environment:
      POSTGRES_USER: mirahub
      POSTGRES_PASSWORD: mirahub123
      POSTGRES_DB: mirahub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql

  app:
    build: .
    container_name: mirahub_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://mirahub:mirahub123@db:5432/mirahub?sslmode=disable
      JWT_SECRET: supersecretkey
      EMAIL_USER: watipasochirambo5@gmail.com
      EMAIL_PASS: sdhicazyhkcvcxcv
      RESEND_API_KEY: re_AfhLcttG_HN9XnQTBkvZXjARSQ7FYL4PK
    depends_on:
      - db
    command: [ "./mirahub-app" ]

volumes:
  db_data:
